---
# Prereqs
- name: generate teardown script
  template: src=teardown_logstash-agent.sh.j2 dest={{ logstash_agent_base_install_dir }}/teardown_logstash-agent_{{ logstash_agent_version }}.sh owner=root group=root mode=0750
- name: create logstash agent group
  group: name={{ logstash_agent_group }} state=present
  when: logstash_agent_group != "root"
- name: create logstash agent user
  user: name={{ logstash_agent_user }} state=present createhome=no shell=/bin/bash group={{ logstash_agent_group }}
  when: logstash_agent_user != "root"
- name: create logstash-agent logs directory
  file: dest={{ logstash_agent_base_logs_dir }}/logstash-agent state=directory owner={{ logstash_agent_user }} group={{ logstash_agent_group }}

# Online Install
- name: online install | download logstash
  get_url: url=https://download.elasticsearch.org/logstash/logstash/logstash-{{ logstash_agent_version }}.tar.gz dest=/var/tmp/logstash-{{ logstash_agent_version }}.tar.gz
  when: logstash_agent_online_install
- name: online install | extract logstash installation
  unarchive: src=/var/tmp/logstash-{{ logstash_agent_version }}.tar.gz copy=no dest={{ logstash_agent_base_install_dir }}/ mode=0700 creates={{ logstash_agent_base_install_dir }}/logstash-{{ logstash_agent_version }}/bin/logstash
  notify:
    - restart logstash-agent
  when: logstash_agent_online_install

# Offline Install
- name: offline install | copy and extract logstash installation
  unarchive: src={{ logstash_agent_installer_path }} dest={{ logstash_agent_base_install_dir }}/ mode=0700 creates={{ logstash_agent_base_install_dir }}/logstash-{{ logstash_agent_version }}/bin/logstash
  notify:
    - restart logstash-agent
  when: not logstash_agent_online_install

# Configure
- name: create logstash-agent configuration directory
  file: path={{ logstash_agent_base_install_dir }}/logstash-{{ logstash_agent_version }}/conf state=directory owner={{ logstash_agent_user }} group={{ logstash_agent_group }}
- name: install logstash agent startup script
  template: src=logstash-agent-sysvinit.j2 dest=/etc/init.d/logstash-agent owner=root group=root mode=0755
  notify:
    - restart logstash-agent
# Copy input configuration
- name: copy input and filter configuration
  copy: src={{ logstash_agent_config }} dest={{ logstash_agent_base_install_dir }}/logstash-{{ logstash_agent_version }} owner={{ logstash_agent_user }} group={{ logstash_agent_user }} mode=0755
  notify:
    - restart logstash-agent

# Create output configuration
- name: install logstash agent configuration
  template: src=output.conf.j2 dest={{ logstash_agent_base_install_dir }}/logstash-{{ logstash_agent_version }}/conf/output.conf owner={{ logstash_agent_user }} group={{ logstash_agent_group }} mode=0755
  notify:
    - restart logstash-agent
- name: grant directory permissions to logstash agent user for installation directory
  file: path={{ logstash_agent_base_install_dir }}/logstash-{{ logstash_agent_version }} owner={{ logstash_agent_user }} group={{ logstash_agent_group }} recurse=true

- name: create symlink to logstash agent installation
  file: src={{ logstash_agent_base_install_dir }}/logstash-{{ logstash_agent_version }} path={{ logstash_agent_base_install_dir }}/logstash-agent state=link force=yes
# FIX: Patch for 1.4.0 issue when overriding JAVA_HOME (See https://logstash.jira.com/browse/LOGSTASH-1984)
- name: patching logstash 1.4.0 bug LOGSTASH-1984
  copy: src=logstash.lib.sh dest={{ logstash_agent_base_install_dir }}/logstash-{{ logstash_agent_version }}/bin/logstash.lib.sh owner={{ logstash_agent_user }} group={{ logstash_agent_user }} mode=0755
  when: logstash_agent_version == "1.4.0" and logstash_agent_java_home
# Run
- name: ensure logstash agent is started and starts on boot
  service: name=logstash-agent state=started enabled=yes
